NumPy, short for Numerical Python, is the fundamental package required for high performance scientific computing and data analysis.

### The NumPy ndarray: A Multidimensional Array Object
One of the key featured of NumPy is it N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python.<br>
Arrays enable one to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements

#### Creating ndarrays

In [53]:
import numpy as np

In [54]:
#List
data = [6, 7.5, 8, 0, 1]
data

[6, 7.5, 8, 0, 1]

In [55]:
# Array from list
arr1 = np.array(data)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [56]:
# Nested squences, like lists of multiple lengths converted into a multidimenstional array
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]

arr2 =np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
#Check array dimension
arr2.ndim

2

arr2 has 2- dimensions meaning the x and y axis are present

In [58]:
arr1.ndim

1

In [59]:
#Array shape
arr2.shape

(2, 4)

arr2 has the shape (2,4) meaning two rows and 4 columns

In [60]:
arr1.shape

(5,)

In [61]:
#check array datatype
arr2.dtype

dtype('int32')

In [62]:
arr1.dtype

dtype('float64')

In [63]:
# Create array of 0s
np.zeros(10) # 1-dimensional array with 10 variables

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [65]:
# 1s array
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [66]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [67]:
# identity matrix
np.eye (3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
'''
empty - creates new arrays by allocating a new memory, but do not populate with any values likezeros or ones. 
Each element of this array will contain whatever values were already present inthe memory location allocated for the array, which could be any abitrary values.

'''
arr =np.empty((2,3,2))
arr

array([[[1.50107827e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.16709769e-312, 1.02309039e+166]],

       [[8.69018667e-043, 2.65007723e-032],
        [2.21387076e-052, 1.51818383e-047],
        [3.70003359e-033, 4.03642256e+175]]])

In [69]:
#check dimension
arr.ndim

3

This is a 3 dimensional array.<br>
- The first dimension has a size of 2.<br>
- The second dimension has a size of 3 <br>
- The third dimension has a size of 2

In [70]:
#shape
arr.shape

(2, 3, 2)

In [71]:
# Array range
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [72]:
arr1 = np.array ([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [73]:
arr1.dtype

dtype('float64')

In [74]:
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [75]:
arr2.dtype

dtype('int32')

Data types are what make Numpy so powerful and flexible. In most cases they map directly onto an underlying machine representation, which makes it easy to ready and write binary streams of data to disk and also to connect to code written in a low-level language like C or Fortran.<br>
The numerical dtypes are named the same way: a type name followed by a number indicating the number of bits per element.

In [76]:
# Convert/cast an array from one dtype to another using astype() method
arr =np.array ([1, 2, 3, 4, 5])

#check dtype
arr.dtype


dtype('int32')

In [77]:
#covert data type to float
float_arr = arr.astype(np.float64)

In [78]:
#Check the data type
float_arr.dtype

dtype('float64')

In [79]:
arr_flt = np.array ([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

#check data type
arr_flt.dtype

dtype('float64')

In [80]:
# convert data type from float to int
arr_flt.astype(np.int64)
arr_flt

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

well, code above did not produce the expected results

In [82]:
# string data type array
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype =np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [83]:
# convert the numeric string to float
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

### Operations between Arrays and Scalars

In [85]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
#multiplication
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [87]:
#subtraction
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [88]:
# operations with scalara
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [89]:
#power
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### Basic indexing and slicing

In [91]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
# Display the 5th element in array
arr[5]


5

In [96]:
#display the fifth to 7th elemets in array
arr[5:8]

array([5, 6, 7])

In [100]:
# replace the 5th to 7th elements with assigned value
arr[5:8] =10
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [102]:
arr_slice = arr[5:8]
arr_slice

array([10, 10, 10])

In [103]:
# Display the first element
arr_slice[1]

10

In [104]:
# aloocate all values in the array with the assigned value
arr_slice[:] = 64
arr_slice

array([64, 64, 64])

In [105]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [107]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
# Second element in the array
arr2d[2]

array([7, 8, 9])

In [111]:
# Element on the first row, second column
arr2d[0,2]

3

With higher dimesnion arrays, there are may options. In a twoo-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays.<br>

Illustration of indexing on a 2D array: <br>
![alt text](image.png)


In [116]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
'''
Array slicing:

Select a sub-array from the third row (index 2 because indexing starts from 0) to the end of the array,
and from the second column to the end of the array
''' 
arr2d[2:,1:]

array([[8, 9]])

In [119]:
'''
Array slicing

Select all rows 
and all columns before the second column (means the first column, index 0 and exclude index 1)
'''
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [120]:
'''
Array slicing

Select all rows from the second row
Select all columns before the third column
'''

arr2d[1:, :2]

array([[4, 5],
       [7, 8]])

In [124]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [125]:
arr2d[2:, :]

array([[7, 8, 9]])

In [127]:
arr2d[1:2,:2]

array([[4, 5]])

![alt text](image-1.png)

### Boolean Indexing

In [122]:
#generate random normally distributed data
data = np.random.randn(7,4)
data

array([[ 0.63906208, -1.25418727, -0.16106286,  0.58722444],
       [ 0.56494685,  0.52879692,  0.21698078, -2.12785894],
       [ 2.22951464, -0.1452791 , -0.78995531,  1.02214131],
       [ 0.26176037,  2.18088813,  1.15537614,  2.46072673],
       [ 1.01189512, -0.55732386, -1.86816361, -1.03321549],
       [-0.13700066, -0.85394646, -0.55341342, -0.42242617],
       [-0.17842698,  1.77158914,  1.13384318, -0.74926553]])

'randn()' function generates an array of random numbers drawn from a standard normal distribution (mean = 0, standard deviation =1)

In [133]:
names = np.array (['Grace', 'Jill','Andrew','Jim', 'Jim', 'Esther','Sally'])
names

array(['Grace', 'Jill', 'Andrew', 'Jim', 'Jim', 'Esther', 'Sally'],
      dtype='<U6')

In [114]:
arr.ndim

1

In [131]:
'''
Suppose each name corresponds to a row in the data array. 
If we wanted to select all the rows with corresponding name 'Grace'. Like arithmetic operations,
comparisons (such as ==) with arrays are also vectorized.
Thus, compating names with the string 'Grace' yeaild a boolean array
'''
names == 'Grace'


array([ True, False, False, False, False, False, False])

In [132]:
# This boolean array can be passed when indexing the array
data [names == 'Grace']

array([[ 0.63906208, -1.25418727, -0.16106286,  0.58722444]])

In [134]:
data [names == 'Jim']

array([[ 0.26176037,  2.18088813,  1.15537614,  2.46072673],
       [ 1.01189512, -0.55732386, -1.86816361, -1.03321549]])

In [135]:
#slicing
data[names == 'Jim', 2:]

array([[ 1.15537614,  2.46072673],
       [-1.86816361, -1.03321549]])

In [138]:
data[names == 'Jim', 3:]

array([[ 2.46072673],
       [-1.03321549]])

In [139]:
data[names == 'Jim', 3]

array([ 2.46072673, -1.03321549])

In [140]:
names != 'Jim'

array([ True,  True,  True, False, False,  True,  True])